services:
  minecraft:
    build: .
    container_name: minecraft
    restart: always
    ports:
      - "25565:25565"
      - "54329:54329"
    volumes:
      - "minecraft_world:/server"

volumes:
  minecraft_world:
