  
FROM python

# RUN mkdir /minecraft
WORKDIR /minecraft

# RUN apt-get update -y
# RUN apt-get upgrade -y
# RUN wget https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.16.3-34.1.25/forge-1.16.3-34.1.25-installer.jar
# RUN apt-get install nano -y

EXPOSE 25565

# ENV PATH="${PATH}:/sinostec/server/app/node-v12.16.1-linux-x64/bin"